
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqjrguqzmpadmglkuvpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxanJndXF6bXBhZG1nbGt1dnBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMjc1OTAsImV4cCI6MjA1OTYwMzU5MH0.i7zvoSMoGCekJHnCxCM3fstRJ2oMdA_yp7N92NoKO3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage,
  }
});

// Define database schema types for TypeScript support
export type Tables = {
  cars: {
    id: string;
    user_id: string;
    make: string;
    model: string;
    year: number;
    price: number;
    mileage: number;
    transmission: string;
    fuel_type: string;
    description?: string;
    availability: string;
    created_at: string;
    updated_at: string;
  };
  car_images: {
    id: string;
    car_id: string;
    url: string;
    is_primary?: boolean;
    created_at: string;
  };
  profiles: {
    id: string;
    first_name?: string;
    last_name?: string;
    phone?: string;
    role: 'superadmin' | 'admin' | 'member';
    is_approved?: boolean;
    created_at: string;
    updated_at: string;
  };
  inquiries: {
    id: string;
    car_id?: string;
    name: string;
    email: string;
    phone?: string;
    message: string;
    status: string;
    created_at: string;
  };
  sell_car_requests: {
    id: string;
    name: string;
    email: string;
    phone: string;
    make: string;
    model: string;
    year: number;
    mileage: number;
    fuel_type: string;
    transmission: string;
    additional_info?: string;
    status: string;
    created_at: string;
  };
  invitations: {
    id: string;
    email: string;
    token: string;
    role: 'superadmin' | 'admin' | 'member';
    created_by: string;
    used?: boolean;
    created_at: string;
    expires_at: string;
  };
}
