// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqjrguqzmpadmglkuvpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxanJndXF6bXBhZG1nbGt1dnBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMjc1OTAsImV4cCI6MjA1OTYwMzU5MH0.i7zvoSMoGCekJHnCxCM3fstRJ2oMdA_yp7N92NoKO3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);